services:
  db:
    image: mysql:8.0
    container_name: travel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: travel_app
      MYSQL_USER: travel
      MYSQL_PASSWORD: travelpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ops/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel-api
    restart: unless-stopped
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: travel
      DB_PASSWORD: travelpass
      DB_NAME: travel_app
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db_data:
